import { createHash } from 'node:crypto';
import { readdir, readFile, rename, writeFile } from 'node:fs/promises';
import path from 'node:path';
import sharp from 'sharp';

const optimizationVersion = 'max-2400-q82-v1';
const supportedExtensions = new Set([
  '.avif',
  '.jpeg',
  '.jpg',
  '.png',
  '.webp',
]);
const writeChanges = process.argv.includes('--write');
const recordCurrent = process.argv.includes('--record-current');
const targetArgument = process.argv.find((argument) =>
  argument.startsWith('--target='),
);
const maxDimensionArgument = process.argv.find((argument) =>
  argument.startsWith('--max-dimension='),
);
const qualityArgument = process.argv.find((argument) =>
  argument.startsWith('--quality='),
);

const targetRoot = targetArgument?.split('=')[1] ?? 'app/images';
const maxDimension = Number(maxDimensionArgument?.split('=')[1] ?? 2400);
const quality = Number(qualityArgument?.split('=')[1] ?? 82);
const minSavingsRatio = 0.02;
const manifestPath = path.join(
  process.cwd(),
  'app',
  'data',
  'image-optimization-manifest.json',
);

function formatBytes(bytes) {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / 1024 / 1024).toFixed(1)} MB`;
}

function digest(buffer) {
  return createHash('sha256').update(buffer).digest('hex');
}

async function collectImages(directory) {
  const entries = await readdir(directory, { withFileTypes: true });
  const files = [];

  for (const entry of entries) {
    const entryPath = path.join(directory, entry.name);

    if (entry.isDirectory()) {
      files.push(...(await collectImages(entryPath)));
      continue;
    }

    if (
      entry.isFile() &&
      supportedExtensions.has(path.extname(entry.name).toLowerCase())
    ) {
      files.push(entryPath);
    }
  }

  return files.sort();
}

async function readManifest() {
  try {
    const manifest = JSON.parse(await readFile(manifestPath, 'utf8'));
    const settingsMatch =
      manifest.version === optimizationVersion &&
      manifest.maxDimension === maxDimension &&
      manifest.quality === quality;
    return settingsMatch ? manifest.files : {};
  } catch {
    return {};
  }
}

async function writeManifest(files) {
  const orderedFiles = Object.fromEntries(
    Object.entries(files).sort(([left], [right]) => left.localeCompare(right)),
  );
  const manifest = {
    description:
      'Hashes of web-ready portfolio images. Generated by pnpm image:optimize; do not edit by hand.',
    version: optimizationVersion,
    maxDimension,
    quality,
    files: orderedFiles,
  };
  await writeFile(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`);
}

function createPipeline(filePath, metadata, input, outputQuality = quality) {
  const extension = path.extname(filePath).toLowerCase();
  const shouldResize =
    Math.max(metadata.width ?? 0, metadata.height ?? 0) > maxDimension;
  let pipeline = sharp(input, { limitInputPixels: false }).rotate();

  if (shouldResize) {
    pipeline = pipeline.resize({
      width: maxDimension,
      height: maxDimension,
      fit: 'inside',
      withoutEnlargement: true,
    });
  }

  // Sharp removes EXIF, IPTC and XMP metadata unless withMetadata() is used.
  if (extension === '.jpg' || extension === '.jpeg') {
    return {
      output: pipeline.jpeg({
        quality: outputQuality,
        mozjpeg: true,
        progressive: true,
      }),
      shouldResize,
    };
  }

  if (extension === '.webp') {
    return {
      output: pipeline.webp({
        quality: outputQuality,
        alphaQuality: 90,
        effort: 6,
      }),
      shouldResize,
    };
  }

  if (extension === '.avif') {
    return {
      output: pipeline.avif({ quality: 52, effort: 4 }),
      shouldResize,
    };
  }

  return {
    output: pipeline.png({
      compressionLevel: 9,
      effort: 10,
      adaptiveFiltering: true,
    }),
    shouldResize,
  };
}

const imageFiles = await collectImages(targetRoot);
const previousManifest = await readManifest();
const nextManifest = {};
const results = [];
let originalBytes = 0;
let optimizedBytes = 0;
let skipped = 0;

for (const filePath of imageFiles) {
  const originalBuffer = await readFile(filePath);
  const relativePath = path.relative(process.cwd(), filePath);
  const originalHash = digest(originalBuffer);
  originalBytes += originalBuffer.length;

  let metadata;
  const manifestMatches = previousManifest[relativePath] === originalHash;

  if (manifestMatches) {
    metadata = await sharp(originalBuffer, {
      limitInputPixels: false,
    }).metadata();
  }

  const alreadyWithinDimensions =
    !metadata ||
    Math.max(metadata.width, metadata.height) <= maxDimension;

  if (recordCurrent || (manifestMatches && alreadyWithinDimensions)) {
    nextManifest[relativePath] = originalHash;
    optimizedBytes += originalBuffer.length;
    skipped += 1;
    continue;
  }

  metadata ??= await sharp(originalBuffer, {
    limitInputPixels: false,
  }).metadata();
  const { output, shouldResize } = createPipeline(
    filePath,
    metadata,
    originalBuffer,
  );
  let optimizedBuffer = await output.toBuffer();
  const extension = path.extname(filePath).toLowerCase();
  const supportsLowerQualityFallback =
    extension === '.jpg' ||
    extension === '.jpeg' ||
    extension === '.webp' ||
    extension === '.avif';

  if (
    shouldResize &&
    optimizedBuffer.length >= originalBuffer.length &&
    supportsLowerQualityFallback
  ) {
    const fallback = createPipeline(
      filePath,
      metadata,
      originalBuffer,
      Math.max(72, quality - 8),
    );
    optimizedBuffer = await fallback.output.toBuffer();
  }
  const savedBytes = originalBuffer.length - optimizedBuffer.length;
  const savingsRatio = savedBytes / originalBuffer.length;
  const hasEmbeddedMetadata = Boolean(
    metadata.exif || metadata.iptc || metadata.xmp,
  );
  // Never replace an already-efficient source with a larger file. Metadata is
  // stripped when doing so also produces a smaller published copy.
  const shouldWrite =
    savedBytes > 0 &&
    (shouldResize || hasEmbeddedMetadata || savingsRatio >= minSavingsRatio);
  const publishedBuffer = shouldWrite ? optimizedBuffer : originalBuffer;

  optimizedBytes += publishedBuffer.length;
  nextManifest[relativePath] = digest(publishedBuffer);

  if (shouldWrite && writeChanges) {
    const temporaryPath = `${filePath}.tmp-optimized`;
    await writeFile(temporaryPath, optimizedBuffer);
    await rename(temporaryPath, filePath);
  }

  results.push({
    path: relativePath,
    before: originalBuffer.length,
    after: publishedBuffer.length,
    saved: shouldWrite ? savedBytes : 0,
    changed: shouldWrite,
  });
}

if (writeChanges || recordCurrent) {
  await writeManifest(nextManifest);
}

const changedResults = results.filter((result) => result.changed);

console.log(
  recordCurrent
    ? 'Recorded the current image set without recompressing it.'
    : writeChanges
      ? 'Optimized changed and new images in place.'
      : 'Dry run only. Re-run with --write to update files.',
);
console.log(`Scanned: ${imageFiles.length}`);
console.log(`Skipped as already optimized: ${skipped}`);
console.log(`Changed: ${changedResults.length}`);
console.log(`Before: ${formatBytes(originalBytes)}`);
console.log(`After: ${formatBytes(optimizedBytes)}`);
console.log(`Savings: ${formatBytes(originalBytes - optimizedBytes)}`);

if (changedResults.length > 0) {
  console.table(
    changedResults.slice(0, 80).map((result) => ({
      saved: formatBytes(result.saved),
      before: formatBytes(result.before),
      after: formatBytes(result.after),
      path: result.path,
    })),
  );
}
